import { useState } from "react";
import { Alert, LayoutAnimation, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ChevronDown, ChevronUp, Copy, Trash2 } from "lucide-react-native";
import * as Clipboard from "expo-clipboard";
import { COLORS, FONTS, FONT_SIZES, SPACING } from "@/constants/theme";

export interface ProviderCardRow { label: string; value: string }

export function CollapsibleProviderCard({ title, status, subtitle, rows, logs = [], error, onDelete, onLongPress }: { title: string; status: "AVAILABLE" | "ERROR" | "NOT DETECTED"; subtitle?: string; rows: ProviderCardRow[]; logs?: string[]; error?: string; onDelete?: () => void; onLongPress?: () => void }) {
  const [expanded, setExpanded] = useState(false);
  const logLines = [...rows.map(row => `${row.label}: ${row.value}`), ...logs].slice(0, 1500);
  const toggle = () => { LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut); setExpanded(value => !value); };
  return <View style={styles.wrapper}>
    <Pressable style={styles.heading} onPress={toggle} onLongPress={onLongPress}><View><Text style={styles.title}>{title}</Text>{subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}</View><View style={styles.headingRight}><Text style={status === "AVAILABLE" ? styles.available : status === "ERROR" ? styles.errorStatus : styles.missing}>{status}</Text>{onDelete ? <Pressable onPress={onDelete} hitSlop={8}><Trash2 size={15} color={COLORS.error} /></Pressable> : null}{expanded ? <ChevronUp size={18} color={COLORS.textDim} /> : <ChevronDown size={18} color={COLORS.textDim} />}</View></Pressable>
    {expanded ? <View style={styles.body}>{error ? <Text style={styles.errorText}>{error}</Text> : null}{logLines.length ? <View style={styles.logs}><View style={styles.logsHeader}><Text style={styles.logsTitle}>LATEST LOGS · {logLines.length}</Text><Pressable accessibilityRole="button" accessibilityLabel={`Copy ${title} logs`} style={styles.copyButton} hitSlop={8} onPress={async () => { await Clipboard.setStringAsync(logLines.join("\n")); Alert.alert("Copied", `${title} logs copied to clipboard.`); }}><Copy size={14} color={COLORS.primary} /></Pressable></View><ScrollView style={styles.logScroll} nestedScrollEnabled showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled">{logLines.map((item, index) => <Text key={`log-${index}`} selectable style={styles.logText}>{item}</Text>)}</ScrollView></View> : null}</View> : null}
  </View>;
}

const styles = StyleSheet.create({ wrapper: { marginHorizontal: -SPACING.md, marginBottom: SPACING.md }, heading: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: SPACING.md, paddingVertical: 8 }, headingRight: { flexDirection: "row", alignItems: "center", gap: 8 }, title: { color: COLORS.text, fontFamily: FONTS.monoBold, fontSize: FONT_SIZES.body }, subtitle: { color: COLORS.textDim, fontFamily: FONTS.mono, fontSize: FONT_SIZES.tiny, marginTop: 3 }, available: { color: COLORS.success, fontFamily: FONTS.monoBold, fontSize: FONT_SIZES.tiny }, errorStatus: { color: COLORS.error, fontFamily: FONTS.monoBold, fontSize: FONT_SIZES.tiny }, missing: { color: COLORS.textDim, fontFamily: FONTS.monoBold, fontSize: FONT_SIZES.tiny }, body: { backgroundColor: COLORS.surface, borderColor: COLORS.border, borderTopWidth: 1, borderBottomWidth: 1, padding: SPACING.md, borderRadius: 0 }, row: { flexDirection: "row", justifyContent: "space-between", borderBottomColor: COLORS.border, borderBottomWidth: 1, paddingVertical: 9 }, label: { color: COLORS.textDim, fontFamily: FONTS.mono, fontSize: FONT_SIZES.small }, value: { color: COLORS.text, fontFamily: FONTS.monoBold, fontSize: FONT_SIZES.small, maxWidth: "60%", textAlign: "right" }, logs: { marginTop: SPACING.md, marginHorizontal: -SPACING.md }, logsHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingRight: SPACING.md }, logsTitle: { color: COLORS.primary, fontFamily: FONTS.monoBold, fontSize: FONT_SIZES.tiny, marginBottom: 6, paddingHorizontal: SPACING.md }, copyButton: { padding: 4, marginBottom: 6 }, logScroll: { maxHeight: 260, backgroundColor: COLORS.background, borderTopWidth: 1, borderBottomWidth: 1, borderColor: COLORS.border, paddingHorizontal: SPACING.md, paddingVertical: SPACING.sm }, logText: { color: COLORS.textDim, fontFamily: FONTS.mono, fontSize: FONT_SIZES.tiny, lineHeight: 16 }, errorText: { color: COLORS.error, fontFamily: FONTS.mono, fontSize: FONT_SIZES.small, marginBottom: SPACING.sm } });
